include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    constant_identifier_names: false

formatter:
  page_width: 80