name: mongol_code
description: Unicode conversion package for traditional Mongolian scripts
version: 0.3.0-nullsafety.0
homepage: https://github.com/suragch/mongol_code

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.11
