name: mongol_code
description: Unicode conversion package for traditional Mongolian scripts
version: 0.1.0
homepage: https://github.com/suragch/mongol_code
author: Suragch <studymongolian@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
