name: mongol_code
description: Unicode conversion package for traditional Mongolian scripts
version: 0.3.0
homepage: https://github.com/suragch/mongol_code

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
