import '../menksoft/menksoft.dart';
import 'mongol.dart';

const Map<int, int> unicodeToMenksoftPunctuation = {
  Mongol.verticalComma: Menksoft.fullWidthComma,
  Mongol.verticalColon: Menksoft.colon,
  Mongol.fullwidthSemicolon: Menksoft.semicolon,
  Mongol.fullwidthExclamation: Menksoft.exclamation,
  Mongol.fullwidthQuestion: Menksoft.question,
  Mongol.verticalEmDash: Menksoft.emDash,
  Mongol.verticalEnDash: Menksoft.enDash,
  Mongol.fullwidthLeftParenthesis: Menksoft.leftParenthesis,
  Mongol.fullwidthRightParenthesis: Menksoft.rightParenthesis,
  Mongol.verticalLeftTortoiseShellBracket: Menksoft.leftTortoiseShellBracket,
  Mongol.verticalRightTortoiseShellBracket: Menksoft.rightTortoiseShellBracket,
  Mongol.leftDoubleAngleBracket: Menksoft.leftDoubleAngleBracket,
  Mongol.rightDoubleAngleBracket: Menksoft.rightDoubleAngleBracket,
  Mongol.leftAngleBracket: Menksoft.leftAngleBracket,
  Mongol.rightAngleBracket: Menksoft.rightAngleBracket,
  Mongol.verticalLeftWhiteCornerBracket: Menksoft.leftWhiteCornerBracket,
  Mongol.verticalRightWhiteCornerBracket: Menksoft.rightWhiteCornerBracket,
  Mongol.middleDot: Menksoft.middleDot,
  Mongol.referenceMark: Menksoft.referenceMark,
  Mongol.questionExclamation: Menksoft.questionExclamation,
  Mongol.exclamationQuestion: Menksoft.exclamationQuestion,
  // Mongol.birga: Menksoft.birga, // Handle this in MongolWord
  Mongol.ellipsis: Menksoft.ellipsis,
  Mongol.comma: Menksoft.comma,
  Mongol.fullStop: Menksoft.fullStop,
  Mongol.colon: Menksoft.colon,
  Mongol.fourDots: Menksoft.fourDots,
  Mongol.todoSoftHyphen: Menksoft.todoSoftHyphen,
  Mongol.sibeSyllableBoundaryMarker: Menksoft.sibeSyllableBoundaryMarker,
  Mongol.manchuComma: Menksoft.manchuComma,
  Mongol.manchuFullStop: Menksoft.manchuFullStop,
  Mongol.digitZero: Menksoft.zero,
  Mongol.digitOne: Menksoft.one,
  Mongol.digitTwo: Menksoft.two,
  Mongol.digitThree: Menksoft.three,
  Mongol.digitFour: Menksoft.four,
  Mongol.digitFive: Menksoft.five,
  Mongol.digitSix: Menksoft.six,
  Mongol.digitSeven: Menksoft.seven,
  Mongol.digitEight: Menksoft.eight,
  Mongol.digitNine: Menksoft.nine,
  Mongol.punctuationX: Menksoft.x,
};
